
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cms_starter?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: test
    password: 
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      validation-timeout: 250
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    database: 0
    port: 6379

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

# 阿里云访问密钥
aliyun:
  accessKeyId:
  accessKeySecret: